# Generated by Django 5.1 on 2024-08-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('emotion', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
